### ISSUE TITLE
Just a few questions 

### ISSUE THREAD

**Issue by Botond0207** [ZerXGIT/knxr-antitroll#4]
I just have a few questions since i couldn't get support from your discord server and i didn't want to dm you. I have an issue, when i try to give myself the anti troll status it says that i don't have permission to do it but i highly doubt that because i'm the owner of the server and i'm in group admin. What can cause this and how can i fix that? Also is there a way i can make the script to put the anti troll status on every player that registers for the first time? Thank you in advance for your answers.

Botond

**Comment by ZerXGIT** [comment]
Are you using ESX or something else?

**Comment by Botond0207** [comment]
> Are you using ESX or something else?

Hey! I managed to solve the problem, but i don't remember how. That's why i closed it. But yes, i'm using esx.
